#!/usr/bin/with-contenv bash

echo "Installing Beets & plugins"
pip3 install --no-cache-dir -U \
    beets \
    beetcamp \
	beautifulsoup4 \
	beets-extrafiles \
	discogs-client \
	flask \
	pyacoustid \
	requests \
	unidecode