#!/usr/bin/with-contenv bash

# a function to test if a version number is greater than another version number
function version_ge() { test "$(printf '%s\n' "$@" | sort -V | head -n 1)" == "$1"; }

required_beets_version="1.4.7"

# Get installed beets version
beets_version=$(beet --version 2>/dev/null | grep ^beets | awk '{print $NF}')

if version_ge "$required_beets_version" "$beets_version" ; then
  echo "**** Installing beets-alternatives ****"
  pip3 install --no-cache-dir -U beets-alternatives beets-bandcamp
else
  echo "**** Beets version $beets_version must be at least $required_beets_version ****"
fi

exit 0
